# Week of 2023-04-24 to 2023-05-01 (11)

### GHFirst (3)

- [Revert "Added round_with_scale_factor arg to ATen (#97868)"](https://github.com/pytorch/pytorch/commit/380ccfd44201d5e714c681f56d6f4ffdc9551380)
  - Caused breakages in the glow compiler - see [D45374622](https://www.internalfb.com/diff/D45374622) for more details ([comment](https://github.com/pytorch/pytorch/pull/97868#issuecomment-1528073566))
- [Revert "Do not assume static by default when exporting (#99554)"](https://github.com/pytorch/pytorch/commit/d0886f686e2c2083dff8296b7402d02670ab17a4)
  - Break internal build ([comment](https://github.com/pytorch/pytorch/pull/99554#issuecomment-1519597275))
- [Revert "Delete tracing_mode argument to export (#99555)"](https://github.com/pytorch/pytorch/commit/c83e1f517d8a1bfe825a9cd70f7a9e3b90301402)
  - Break internal build ([comment](https://github.com/pytorch/pytorch/pull/99555#issuecomment-1519607725))

### Ignored Signal (1)

- [Revert "[c10d] Comment out ddp_hook_with_optimizer_parity tests (#100215)"](https://github.com/pytorch/pytorch/commit/9609aeefbb0b31ffa801034c2daa3fecc6804707)
  - Sorry for revert your change, but it breaks lint, please run lintrunner -a torch/testing/_internal/distributed/distributed_test.py to fix the issue then reland it ([comment](https://github.com/pytorch/pytorch/pull/100215#issuecomment-1526847157))

### No Signal (2)

- [Revert "[CI] Start to collect inference perf with cpp_wrapper ON (#100187)"](https://github.com/pytorch/pytorch/commit/90c44b134a75fae14850b85c55d8b645da2c0637)
  - scheduled dashboard run failed ([comment](https://github.com/pytorch/pytorch/pull/100187#issuecomment-1527453462))
- [Revert "Migrate jobs from windows.4xlarge to windows.4xlarge.nonephemeral instances (#100091)"](https://github.com/pytorch/pytorch/commit/e5291e633fca9639ace4fb4585e1bb0b9dca9e95)
  - CPU jobs start failing in trunk due to some error in MSVC setup ([comment](https://github.com/pytorch/pytorch/pull/100091#issuecomment-1523920543))

### Got @pytorchbot revert command, but no corresponding commit (3)

- cannot find commit corresponding to @pytorchbot revert comment
  - broke fbcode ([comment](https://github.com/pytorch/pytorch/pull/99931#issuecomment-1526145702))
- cannot find commit corresponding to @pytorchbot revert comment
  - Break internal build ([comment](https://github.com/pytorch/pytorch/pull/99554#issuecomment-1519615995))
- cannot find commit corresponding to @pytorchbot revert comment
  - i messed up ([comment](https://github.com/pytorch/pytorch/pull/99739#issuecomment-1525833096))

### Weird (2)

- [Revert "Run test_fx_to_onnx_with_onnxruntime serially (#100298)"](https://github.com/pytorch/pytorch/commit/9075e3c2c631e0c52b0bb5f2d8748ac4b5d2bd24)
  - No need as https://github.com/pytorch/pytorch/pull/100297 has been landed ([comment](https://github.com/pytorch/pytorch/pull/100298#issuecomment-1528476786))
- [Revert "Move win-vs2019 build and test to unstable (#100281)"](https://github.com/pytorch/pytorch/commit/3d55bce3bf5fe5cb0d654ecb48100eeac1d2dfa0)
  - All runners has been updated ([comment](https://github.com/pytorch/pytorch/pull/100281#issuecomment-1528622556))
