# Week of 2024-05-13 to 2024-05-20 (20)

### GHFirst (7)

- [Revert "Fix aarch64 debug build with GCC (#126290)"](https://github.com/pytorch/pytorch/commit/875221dedf9eeda567b2327336a2aedc681b9cdc)
  - There seems to be a mis-match closing curly bracket here and it breaks some internal build in D57474505 ([comment](https://github.com/pytorch/pytorch/pull/126290#issuecomment-2118246756))
- [Revert "Remove redundant serialization code (#126249)"](https://github.com/pytorch/pytorch/commit/f89500030bb6909569668ba47b9895780dc44052)
  - Sorry for reverting your change but it is failing sigmoid/frontend:serialization_test internally ([comment](https://github.com/pytorch/pytorch/pull/126249#issuecomment-2118233656))
- [Revert "[inductor][cpp] GEMM template (infra and fp32) (#124021)"](https://github.com/pytorch/pytorch/commit/337830f6574057b5e04a7f2c0aa671a575058add)
  - Unfortunately, the new tests are still failing internally ([comment](https://github.com/pytorch/pytorch/pull/124021#issuecomment-2116415398))
- [Revert "[inductor][cpp] epilogue support for gemm template (#126019)"](https://github.com/pytorch/pytorch/commit/4a5ef0b7938f9b5b6cb2f1cd200f925059ba3f59)
  - Sorry for reverting your change, but the dependency PR https://github.com/pytorch/pytorch/pull/124021 is going to be revert ([comment](https://github.com/pytorch/pytorch/pull/126019#issuecomment-2116408137))
- [Revert "[inductor][cpp] bf16/fp16 gemm template computed with fp32 w/o epilogue fusion (#126068)"](https://github.com/pytorch/pytorch/commit/59ca0d8c141d016f5dcfaf76dfcb63949ee888fd)
  - Sorry for reverting your change, but the dependency PR https://github.com/pytorch/pytorch/pull/124021 is going to be revert ([comment](https://github.com/pytorch/pytorch/pull/126019#issuecomment-2116408137))
- [Revert "Remove deprecated _aminmax operator (#125995)"](https://github.com/pytorch/pytorch/commit/315389bfed3a0b29752997862e18681169ebd501)
  - Sorry for reverting your change but we need to reland this after I get rid of all usage of _aminmax internally in Meta ([comment](https://github.com/pytorch/pytorch/pull/125995#issuecomment-2113769497))
- [Revert "[inductor][cpp] GEMM template (infra and fp32) (#124021)"](https://github.com/pytorch/pytorch/commit/b6d8b256e6a46f032a17ca167f4c2ae9aa67755d)
  - Sorry for reverting your change, but it is failing inductor.test_unbacked_symints.TestUnbackedSymintsCPU::test_autotuning_cpu ([comment](https://github.com/pytorch/pytorch/pull/124021#issuecomment-2111318883))

### Ignored Signal (4)

- [Revert "[FSDP2] Fixed 2D clip grad norm test (#126497)"](https://github.com/pytorch/pytorch/commit/d782e43464bc939429054e3373af8cf80554fc45)
  - reverting to check if might have introduced inductor cuda 12 issues ([comment](https://github.com/pytorch/pytorch/pull/126497#issuecomment-2118338716))
- [Revert "Initial implementation of AdaRound (#126153)"](https://github.com/pytorch/pytorch/commit/ae6fdfa53989b3f67ef594dbcfdda9bab98a557a)
  - Sorry for reverting your change but the lint failure is legit because there are more than one lint issues, torch/optim/asgd.py is just the last one ([comment](https://github.com/pytorch/pytorch/pull/126153#issuecomment-2113902522))
- [Revert "Fix aarch64 debug build with GCC (#126290)"](https://github.com/pytorch/pytorch/commit/2086f91c4cd250a66fb57fbc9c09901680a1476d)
  - Indeed lint is broken :/ ([comment](https://github.com/pytorch/pytorch/pull/126290#issuecomment-2113332757))
- [Revert "[CUDA] [CI] Add cu124 docker images  (#125944)"](https://github.com/pytorch/pytorch/commit/fd48fb9930d0582c0ac0e0c6b2e031a43c028cbe)
  - test failure seems related https://hud.pytorch.org/pytorch/pytorch/commit/5fb4a766b88bcf633a23610bd66de0f3020f7c66 https://github.com/pytorch/pytorch/actions/runs/9085206167/job/24972040039 ([comment](https://github.com/pytorch/pytorch/pull/125944#issuecomment-2111321724))

### Landrace (1)

- [Revert "Remove Caffe2 python code (#126035)"](https://github.com/pytorch/pytorch/commit/ed76079af32181dbc4df2c51db90b8ad66174a75)
  - Seems to have introduced lint error: Error: Module 'onnx' has no attribute 'numpy_helper' ([comment](https://github.com/pytorch/pytorch/pull/126035#issuecomment-2110570863))

### No Signal (5)

- [Revert "[Dynamo] Treat integers stored on nn.Modules as dynamic (#126466)"](https://github.com/pytorch/pytorch/commit/71b6459edc19dac02b6e559977a0f615bf451210)
  - Sorry for reverting your change but the ONNX test failure looks legit, not flaky, as it starts failing in trunk https://hud.pytorch.org/pytorch/pytorch/commit/6bb9d6080d33c817fcbf9e5ae8a59b76812a53d2 ([comment](https://github.com/pytorch/pytorch/pull/126466#issuecomment-2119078245))
- [Revert "Add Lowering for FlexAttention Backwards (#125515)"](https://github.com/pytorch/pytorch/commit/0716f75cfb9d287a2dce74d79c8f2b72bd729d6c)
  - Sorry for reverting your change but the newly added test runs out of memory https://hud.pytorch.org/pytorch/pytorch/commit/95b9e981c3ab68fc17f78b8a6bbfd9569745ae4c ([comment](https://github.com/pytorch/pytorch/pull/125515#issuecomment-2114084869))
- [Revert "[Memory Snapshot] Add recordAnnotations to capture record_function annotations (#124179)"](https://github.com/pytorch/pytorch/commit/718bb9016f78f9fee1750977f0ad0539610dbce3)
  - test_tensorexpr.py::TestTensorExprFuser::test_simple_add is causing a segfault https://github.com/pytorch/pytorch/actions/runs/9097383783/job/25007155440 https://hud.pytorch.org/pytorch/pytorch/commit/187aeaeabf612824c2d0e9be72f80ce6612760d4, test was skipped due to bad TD ([comment](https://github.com/pytorch/pytorch/pull/124179#issuecomment-2112948246))
- [Revert "[c10d] Add an option for NAN check on every collective (#125726)"](https://github.com/pytorch/pytorch/commit/20aa7cc6788ff10dee2d927057b10a81af638a32)
  - Sorry for reverting your change, but the new test is failing on both multigpu and rocm distributed, i.e. https://hud.pytorch.org/pytorch/pytorch/commit/c712b0f8a3e72feda9a90e22e9f36bd102b7d25e ([comment](https://github.com/pytorch/pytorch/pull/125726#issuecomment-2110646075))
- [Revert "[optim] add fused_adagrad support for CPU device (#124905)"](https://github.com/pytorch/pytorch/commit/bd3cbdba2f7a3f69ccdd441c6e88c3f5ebe5df44)
  - Sorry for reverting your change, but it is failing distributed multigpu test in trunk https://hud.pytorch.org/pytorch/pytorch/commit/1c3fe8403365db3cc9b75524ae742e3027b745e2 ([comment](https://github.com/pytorch/pytorch/pull/124905#issuecomment-2108777063))

### Weird (3)

- [Revert "Fix lint failures coming from #126035 (#126378)"](https://github.com/pytorch/pytorch/commit/cdcba4dee5227519c96a9b50a3955c3519ed97e7)
  - Trying to add yet another lint fix from https://hud.pytorch.org/pr/pytorch/pytorch/126357 and will reland this ([comment](https://github.com/pytorch/pytorch/pull/126378#issuecomment-2114060547))
- [Revert "[optim] Fix: wrong ASGD implementation  (#125440)"](https://github.com/pytorch/pytorch/commit/e3c5d1b7d7645e3e9c9efc71cbbaa77248fda9c2)
  - Sorry for reverting your change but it looks like there is a linter failure coming from this change ([comment](https://github.com/pytorch/pytorch/pull/125440#issuecomment-2113833108))
- [Revert "Switched from parameter in can_cast to from_. (#126030)"](https://github.com/pytorch/pytorch/commit/6065a4d46ec8b4a51315990b8ac05565b5a84708)
  - Sorry for reverting your change but i need to revert it to avoid a diff train conflict with https://github.com/pytorch/pytorch/pull/125995.  Please help rebase and I will reland the change ([comment](https://github.com/pytorch/pytorch/pull/126030#issuecomment-2113757469))
